sqlite:
  :adapter: sqlite
  :dbfile: democracy_in_action.sqlite.db
sqlite3:
  :adapter: sqlite3
  :dbfile: ":memory:"
postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: democracy_in_action_test
  :min_messages: ERROR
mysql:
  :adapter: mysql
  :host: localhost
  :username: rails
  :password:
  :database: democracy_in_action_test
